services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=booking_db'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '54604:3306'
    volumes:
      - './schema/booking_db.sql:/docker-entrypoint-initdb.d/schema.sql'